// AUTO-GENERATED by scripts/sync-legal.mjs — DO NOT EDIT.
// Source of truth: legal/*.md. Run `npm run sync:legal` after editing them.

export const PRIVACY_POLICY = `# Privacy Policy — Nearly Departed

**Effective date:** June 18, 2026
**Last updated:** June 18, 2026

This Privacy Policy explains how **Nearly Departed** ("the App," "we," "us") handles information when you use it. The App is operated by Grave Goods, LLC based in Littleton, Colorado, USA. Contact: admin@gravegoodsgoodies.com.

## The short version

- We do **not** require an account to use the App.
- We do **not** run analytics or advertising SDKs, and we do **not** sell your data.
- We do **not** operate servers that store your personal data. The App talks directly to a small number of public third-party services to fetch maps and burial records.
- Your **location** is used to find notable burials near you, and the coordinates are sent to those public services _as part of a query_ to retrieve results.
- Your **saved favorites** are stored **only on your device**.

## Information we collect and how it's used

**1. Location data.**
If you tap "Use my location," the App requests permission to access your device's location _while you are using the App_ (\`When In Use\`). Your approximate coordinates are used to:

- center the map, and
- query public databases for notable people buried near that point.

To do that, your coordinates are transmitted to the third-party services listed below (e.g. the Wikimedia Query Service) as part of the search request. We do not store your location on our own servers (we have none). You can revoke location access at any time in your device Settings; the App still works if you instead search for a place manually.

**2. Place searches.**
When you use "search anywhere," the text you type (e.g. a city or cemetery name) is sent to our geocoding provider (Komoot/Photon) to convert it into coordinates. We do not store these searches.

**3. Technical information inherent to internet requests.**
When the App contacts a third-party service, that service automatically receives standard network information such as your **IP address** and device/user-agent details, governed by _that service's_ privacy policy (linked below). We do not receive or retain this information.

**4. Favorites and on-device data.**
Any graves you save are stored locally on your device using the operating system's storage. This data is not transmitted to us and is removed if you delete the App.

**5. Accounts (not currently active).**
The App does not currently offer accounts. If and when sign-in (e.g. Apple, Google, or email) is added, we will update this policy to describe what account information is collected (such as your email address and name) and how it is used. Until then, no account data is collected.

## What we do **not** do

- No third-party analytics or tracking SDKs.
- No advertising or advertising identifiers (IDFA).
- No sale or "sharing" of personal information as defined under CCPA/CPRA.
- No collection of contacts, photos, microphone, or background location.

## Third-party services

The App sends requests directly to these services to function. Each has its own privacy policy:

- **Wikimedia Foundation** — Wikidata Query Service and the Wikipedia API, used to find burial records, biographies, and images. https://foundation.wikimedia.org/wiki/Policy:Privacy_policy
- **Komoot (Photon)** — place-name geocoding for "search anywhere." https://www.komoot.com/privacy
- **CARTO** — dark base-map tiles. https://carto.com/privacy/
- **Apple** — operating-system location services and (if enabled later) Sign in with Apple. https://www.apple.com/legal/privacy/

These services may process data outside your country of residence.

## Data retention

We do not maintain servers that store your personal data, so we retain none. On-device data (favorites) persists until you remove it or delete the App.

## Your rights

Depending on where you live, you may have rights to access, correct, delete, or restrict processing of personal data (e.g. under GDPR or CCPA/CPRA). Because we do not store personal data ourselves, most such requests are satisfied by controlling permissions on your device (location) and deleting local data (uninstalling the App). For requests concerning data held by the third-party services above, please contact those providers directly. You may also contact us at admin@gravegoodsgoodies.com.

## Children's privacy

The App is not directed to children under 13 (or the minimum age in your jurisdiction), and we do not knowingly collect personal information from them.

## Security

We use reputable third-party services that transmit data over encrypted (HTTPS) connections. No method of transmission is completely secure, and we cannot guarantee absolute security.

## Changes to this policy

We may update this policy as the App evolves (for example, when accounts are added). We will revise the "Last updated" date above and, for material changes, provide notice in the App.

## Contact

Questions? Contact Grave Goods, LLC at admin@gravegoodsgoodies.com.
`;

export const TERMS_OF_SERVICE = `# Terms of Service — Nearly Departed

**Effective date:** June 18, 2026
**Last updated:** June 18, 2026

These Terms of Service ("Terms") govern your use of the **Nearly Departed** mobile application ("the App"), operated by Grave Goods, LLC ("we," "us"), based in Littleton, Colorado, USA. By downloading or using the App, you agree to these Terms. If you do not agree, do not use the App.

## 1. What the App is

Nearly Departed helps you discover notable people buried near you or near a place you search. Burial records, biographies, images, and map data are drawn from public sources including **Wikidata, Wikipedia, and OpenStreetMap**. The App is provided for **informational and educational purposes only**.

## 2. Eligibility

You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction) to use the App.

## 3. Accuracy of information

Burial records and locations are sourced from **community-maintained, third-party databases and may be incomplete, outdated, or inaccurate.** Map markers reflect cemetery-level coordinates and are approximate — they do **not** indicate an exact plot. **Always verify independently before relying on this information or traveling to a location.** We make no guarantee as to the accuracy, completeness, or availability of any information in the App.

## 4. Respectful and lawful use

Cemeteries are places of remembrance and are often private property with their own rules and hours. You agree that:

- The App does **not** grant you any right of access to any property, grave, or site.
- You will obey all cemetery rules, posted hours, signage, and applicable laws when visiting any location.
- You will treat burial sites, the deceased, and their families with respect.
- You will not use the App to harass, stalk, or disturb any person, or for any unlawful purpose.

## 5. Acceptable use

You agree not to:

- copy, scrape, or systematically extract data from the App except as permitted by the underlying data licenses (Section 7);
- reverse engineer, modify, or create derivative works of the App except as allowed by law;
- interfere with or overload the third-party services the App relies on; or
- use the App in any way that violates these Terms or applicable law.

## 6. Your content (favorites)

Any items you save (e.g. favorites) are stored on your device. You are responsible for your own use of saved information.

## 7. Intellectual property and open-data licenses

The App's design, code, and branding are owned by Grave Goods, LLC and protected by intellectual-property laws. The underlying **data and map content are owned by their respective sources and provided under open licenses**, which you must respect:

- **Wikidata** — CC0 (public domain).
- **Wikipedia** content — CC BY-SA.
- **OpenStreetMap** data — Open Database License (ODbL); © OpenStreetMap contributors.
- Base-map styling provided via **CARTO**.

Attribution to these sources is provided within the App. Your reuse of any underlying data is governed by those licenses, not these Terms.

## 8. Third-party services

The App relies on third-party services (Wikimedia, Komoot/Photon, CARTO, Apple). Your use of those services may be subject to their own terms and privacy policies. We are not responsible for third-party services or their content.

## 9. Disclaimers

THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT INFORMATION WILL BE ACCURATE.

## 10. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, Grave Goods, LLC WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS ARISING FROM YOUR USE OF (OR INABILITY TO USE) THE APP OR YOUR RELIANCE ON ANY INFORMATION IN IT, INCLUDING ANYTHING RELATED TO TRAVELING TO OR VISITING A LOCATION. OUR TOTAL LIABILITY WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID FOR THE APP OR USD $0.

## 11. Indemnification

You agree to indemnify and hold harmless Grave Goods, LLC from any claims or damages arising out of your misuse of the App or violation of these Terms or applicable law.

## 12. Changes and termination

We may update these Terms or modify, suspend, or discontinue the App at any time. Material changes will be noted by the "Last updated" date and, where appropriate, notice in the App. Continued use after changes means you accept them.

## 13. Governing law

These Terms are governed by the laws of the **State of Colorado, USA**, without regard to conflict-of-laws principles, except where your local consumer-protection law requires otherwise.

## 14. Apple App Store

If you obtained the App through the Apple App Store, you acknowledge these Terms are between you and Grave Goods LLC, not Apple, and that Apple is not responsible for the App or its content. Apple is a third-party beneficiary of these Terms and may enforce them.

## 15. Contact

Questions? Contact Grave Goods, LLC at admin@gravegoodsgoodies.com
`;
