// Generates src/content/legal.ts from legal/*.md (the single source of truth).
// Run once:   npm run sync:legal
// Live watch: npm run sync:legal:watch   (regenerates on every .md save → Fast Refresh)
//
// Why a script instead of importing .md directly: babel-plugin-inline-import
// inlines .md at transform time but Metro doesn't track the .md as a dependency,
// so edits stayed invisible until a `-c` cache wipe. Generating a real .ts module
// means Metro sees it change and Fast Refresh just works.

import { readFileSync, writeFileSync, watch } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const DOCS = {
  PRIVACY_POLICY: "legal/privacy-policy.md",
  TERMS_OF_SERVICE: "legal/terms-of-service.md",
};

// Make markdown safe inside a JS template literal.
const escape = (s) =>
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

function generate() {
  const body = Object.entries(DOCS)
    .map(([name, rel]) => {
      const md =
        readFileSync(join(root, rel), "utf8").replace(/\s+$/, "") + "\n";
      return `export const ${name} = \`${escape(md)}\`;`;
    })
    .join("\n\n");

  const out = `// AUTO-GENERATED by scripts/sync-legal.mjs — DO NOT EDIT.
// Source of truth: legal/*.md. Run \`npm run sync:legal\` after editing them.

${body}
`;

  writeFileSync(join(root, "src/content/legal.ts"), out);
  console.log("✓ synced src/content/legal.ts from legal/*.md");
}

generate();

if (process.argv.includes("--watch")) {
  for (const rel of Object.values(DOCS)) {
    watch(join(root, rel), () => {
      try {
        generate();
      } catch (err) {
        console.error("sync-legal failed:", err.message);
      }
    });
  }
  console.log("… watching legal/*.md (Ctrl-C to stop)");
}
